"""STATIC VARIABLES
"""

VERSION = "0.2"

LOG_PATH = "log.txt"
APP_ID = "4YXditjeN6dWnUpkywgxxg"
SECRET = "Ar0b_hapYUTmYZ7QFrBk4saR8HhyZg"

VIDEO_FONT = "resources/MontserratExtrabold.ttf"
FONT_SIZE = 40
FONT_COLOR=(255,255,255,255)
STROKE_WIDTH=5
STROKE_COLOR=(0,0,0,255)
TITLE_BACKGROUND=(230,0,0,255)
TITLE_DURATION=2

MODEL_PATH = "model/vosk-model-en-us-0.42-gigaspeech"
APP_NAME = f"scrapper {VERSION}"

FADE_TO_BLACK_TIME = 1.5
CROSS_FADE_IN_OUT = 0.3

WRAP_TEXT = 20
