"""STATIC VARIABLES
"""

VERSION = "0.2"

LOG_PATH = "log.txt"
APP_ID = "4YXditjeN6dWnUpkywgxxg"
SECRET = "Ar0b_hapYUTmYZ7QFrBk4saR8HhyZg"

VIDEO_FONT = "resources/COOPBL.ttf"
FONT_SIZE = 40
FONT_COLOR=(255,255,255,255)
STROKE_WIDTH=5
STROKE_COLOR=(255,0,0,255)

MODEL_PATH = "model/vosk-model-en-us-0.22"
APP_NAME = f"scrapper {VERSION}"

FADE_TO_BLACK_TIME = 3
